# https://springframework.guru/using-yaml-in-spring-boot-to-configure-logback/
logging:
  file: scrumpoker.log
  pattern:
    console: "%d %-5p [%c %M %L] - %m%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    root: WARN
    mqbdi:
      scrumpoker: DEBUG
spring:
  application:
    name : Scrum Poker Application
  thymeleaf:
    cache: false
    enable: true
    check-template: true
    check-template-location: true
    prefix: classpath:/templates/
    suffix: .html
  jpa:
    generate-ddl: true
    hibernate.ddl-auto: update
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:bootapp;DB_CLOSE_DELAY=-1
    username: sa
    password:

server:
  port : 18080
  error:
    path: /error
    whitelabel.enabled: false
  servlet:
    context-path: /
# http://localhost:18080/swagger-ui/index.html

# https://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-features.html#production-ready-health
management:
  endpoint:
    health:
      show-details: always